
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mateus
 */
public class ConsultaContas extends javax.swing.JFrame {

    private static ConsultaContas instancia;
    private JDialog confirmationDialog;

    /**
     * Creates new form CriarContaCorrente
     */
    public ConsultaContas() {
        initComponents();
        cxNumeroConta.requestFocus();

    }

    public static ConsultaContas getInstance() {
        if (instancia == null) {
            instancia = new ConsultaContas();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotTituloPaginaConsultar = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        Separador = new javax.swing.JSeparator();
        cxNumeroConta = new javax.swing.JTextField();
        txNumeroConta = new javax.swing.JLabel();
        btLimpar1 = new javax.swing.JButton();
        PainelContas = new javax.swing.JScrollPane();
        tbContas = new javax.swing.JTable();
        btDeletar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotTituloPaginaConsultar.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        rotTituloPaginaConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rotTituloPaginaConsultar.setText("| Consultar Contas |");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        cxNumeroConta.setToolTipText("");
        cxNumeroConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cxNumeroContaKeyTyped(evt);
            }
        });

        txNumeroConta.setText("Numero da Conta:");

        btLimpar1.setText("Pesquisar");
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });

        tbContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "Numero da Conta", "Agencia:"
            }
        ));
        tbContas.setColumnSelectionAllowed(true);
        tbContas.getTableHeader().setReorderingAllowed(false);
        PainelContas.setViewportView(tbContas);
        tbContas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btDeletar.setText("Deletar");
        btDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDeletarMouseClicked(evt);
            }
        });
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rotTituloPaginaConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(Separador))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txNumeroConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair)
                        .addContainerGap())
                    .addComponent(PainelContas)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotTituloPaginaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txNumeroConta)
                            .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpar1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelContas, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDeletar)
                            .addComponent(btEditar)
                            .addComponent(btSair))
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
        Principal principal = Principal.getInstance();
        principal.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        pesquisar();

    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeletarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditarActionPerformed

    private void btDeletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeletarMouseClicked
        deletar();
    }//GEN-LAST:event_btDeletarMouseClicked

    private void cxNumeroContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxNumeroContaKeyTyped

        limitaCaracters(evt, cxNumeroConta, 6);


    }//GEN-LAST:event_cxNumeroContaKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PainelContas;
    private javax.swing.JSeparator Separador;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxNumeroConta;
    private javax.swing.JLabel rotTituloPaginaConsultar;
    private javax.swing.JTable tbContas;
    private javax.swing.JLabel txNumeroConta;
    // End of variables declaration//GEN-END:variables

    private void limpar() {

    }

    
    private void pesquisar() {
        String numeroConta = cxNumeroConta.getText();
        BancoContas banco = BancoContas.getBanco();
        List<ContaCorrente> contasCorrente = banco.getBdContasCorrente();
        List<ContaPoupanca> contasPoupanca = banco.getBdContasPoupanca();
        List<ContaPoupancaEspecial> contasPoupancaEspecial = banco.getBdContasPoupancaEspecial();

        DefaultTableModel model = (DefaultTableModel) tbContas.getModel();
        model.setRowCount(0); // Clear existing rows

        for (ContaCorrente conta : contasCorrente) {
            if (conta.getNumero().equals(numeroConta)) {
                Object[] rowData = {"Conta Corrente", conta.getNumero(), conta.getAgencia()};
                model.addRow(rowData);
                return; // No need to check other lists
            }
        }

        for (ContaPoupanca conta : contasPoupanca) {
            if (conta.getNumero().equals(numeroConta)) {
                Object[] rowData = {"Conta Poupança", conta.getNumero(), conta.getAgencia()};
                model.addRow(rowData);
                return; // No need to check other lists
            }
        }

        for (ContaPoupancaEspecial conta : contasPoupancaEspecial) {
            if (conta.getNumero().equals(numeroConta)) {
                Object[] rowData = {"Conta Poupança Especial", conta.getNumero(), conta.getAgencia()};
                model.addRow(rowData);
                return; // No need to check other lists
            }
        }

        JOptionPane.showMessageDialog(this, "Conta não encontrada", "Pesquisar Conta", JOptionPane.INFORMATION_MESSAGE);
    }

    private void deletar() {
        int selectedRow = tbContas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma conta selecionada", "Deletar Conta", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tipoConta = (String) tbContas.getValueAt(selectedRow, 0);
        String numeroConta = (String) tbContas.getValueAt(selectedRow, 1);
        String agencia = (String) tbContas.getValueAt(selectedRow, 2);

        String message = "<html><b>Número da Conta:</b> " + numeroConta + "<br><b>Agência:</b> " + agencia + "<br><br>Tem certeza que deseja deletar a conta?</html>";

        int option = JOptionPane.showConfirmDialog(this, message, "Deletar Conta", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            BancoContas banco = BancoContas.getBanco();
            banco.excluirConta(numeroConta);

            DefaultTableModel model = (DefaultTableModel) tbContas.getModel();
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Conta deletada com sucesso", "Deletar Conta", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void limitaCaracters(KeyEvent evt, JTextField componente, int tamanho) {
        int k = evt.getKeyChar();
        if (Character.isDigit(k)) {
            if (componente.getText().length() == tamanho) {
                evt.consume(); // Impede a entrada adicional de caracteres
            }
        } else {
            evt.consume(); // Impede a entrada de caracteres não numéricos
        }
    }

}
