
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Mateus
 */
public class Principal extends javax.swing.JFrame {

    private static Principal instancia;

    
    public Principal() {
        initComponents();
    }

    public static Principal getInstance() {
        if (instancia == null) {
            instancia = new Principal();
        }
        return instancia;
    }

    public void sair() {
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair",
                "Saida",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == 0) {
            System.exit(0);
            
        }
    }

    /**
     * /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotTituloPrinc = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        mCriarConta = new javax.swing.JMenu();
        iCriarContaCorrente = new javax.swing.JMenuItem();
        sbContasPoupanca = new javax.swing.JMenu();
        iCriarContaPoupanca = new javax.swing.JMenuItem();
        iCriarContaPoupanca1 = new javax.swing.JMenuItem();
        mBuscarConta = new javax.swing.JMenu();
        mOperaçõesBancarias = new javax.swing.JMenu();
        sbTodasContas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        sbMetodosUnicos = new javax.swing.JMenu();
        iTransferencia = new javax.swing.JMenuItem();
        iConsultarLimite = new javax.swing.JMenuItem();
        iCalcularRendimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rotTituloPrinc.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        rotTituloPrinc.setText("Sistema de Gerencia de Contas Bancarias");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        mCriarConta.setText("Criar Contas");

        iCriarContaCorrente.setText("Criar Conta Corrente");
        iCriarContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCriarContaCorrenteActionPerformed(evt);
            }
        });
        mCriarConta.add(iCriarContaCorrente);

        sbContasPoupanca.setText("Contas Poupança");

        iCriarContaPoupanca.setText("Criar Conta Poupança");
        sbContasPoupanca.add(iCriarContaPoupanca);

        iCriarContaPoupanca1.setText("Criar Conta Poupança Especial");
        sbContasPoupanca.add(iCriarContaPoupanca1);

        mCriarConta.add(sbContasPoupanca);

        BarraMenu.add(mCriarConta);

        mBuscarConta.setText("Buscar Contas");
        BarraMenu.add(mBuscarConta);

        mOperaçõesBancarias.setText("Operações Bacarias");

        sbTodasContas.setText("Todas Contas");

        jMenuItem1.setText("Realizar Saque");
        sbTodasContas.add(jMenuItem1);

        jMenuItem2.setText("Realizar Deposito");
        sbTodasContas.add(jMenuItem2);

        jMenuItem3.setText("Consultar Saldo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        sbTodasContas.add(jMenuItem3);

        jMenu5.setText("Todas Contas");

        jMenuItem7.setText("Realizar Saque");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Realizar Deposito");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Consultar Saldo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        sbTodasContas.add(jMenu5);

        mOperaçõesBancarias.add(sbTodasContas);

        sbMetodosUnicos.setText("Métodos Unicos");

        iTransferencia.setText("Realizar Transferencia");
        sbMetodosUnicos.add(iTransferencia);

        iConsultarLimite.setText("Consultar Limite");
        sbMetodosUnicos.add(iConsultarLimite);

        iCalcularRendimento.setText("Calcular Rendimento");
        sbMetodosUnicos.add(iCalcularRendimento);

        mOperaçõesBancarias.add(sbMetodosUnicos);

        BarraMenu.add(mOperaçõesBancarias);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(rotTituloPrinc)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rotTituloPrinc)
                .addGap(111, 111, 111)
                .addComponent(btSair)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void iCriarContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCriarContaCorrenteActionPerformed
        dispose();
        CriarContaCorrente criarContaCorrente = CriarContaCorrente.getInstance();
        criarContaCorrente.setVisible(true);
    }//GEN-LAST:event_iCriarContaCorrenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem iCalcularRendimento;
    private javax.swing.JMenuItem iConsultarLimite;
    private javax.swing.JMenuItem iCriarContaCorrente;
    private javax.swing.JMenuItem iCriarContaPoupanca;
    private javax.swing.JMenuItem iCriarContaPoupanca1;
    private javax.swing.JMenuItem iTransferencia;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mBuscarConta;
    private javax.swing.JMenu mCriarConta;
    private javax.swing.JMenu mOperaçõesBancarias;
    private javax.swing.JLabel rotTituloPrinc;
    private javax.swing.JMenu sbContasPoupanca;
    private javax.swing.JMenu sbMetodosUnicos;
    private javax.swing.JMenu sbTodasContas;
    // End of variables declaration//GEN-END:variables
}
